name: Github Actions CI
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v4
      with:
        root_file: cv.tex
        latexmk_use_lualatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Upload cv.pdf
      run: |
        # configure git
        git config --global user.name "Cheng Xu"
        git config --global user.email "git@xuc.me"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 git@github.com:xu-cheng/website.git "$GITHUB_WORKSPACE/website"
        cp -f cv.pdf "$GITHUB_WORKSPACE/website/file/cv.pdf"
        cd "$GITHUB_WORKSPACE/website"
        git add file/cv.pdf
        git commit -m "[github actions] update cv"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
